spring:
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2
---
server:
  port: 8002
eureka:
  client:
    service-url:
      default-zome: http://localhost:8761/eureka

